import Link from 'next/link'
import { TikkitXLogo } from '@/components/ui/TikkitXLogo'
import SiteFooter from '@/components/SiteFooter'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions — Tikkit X',
  description: 'The terms and conditions governing your use of the Tikkit X event management platform in Pakistan.',
  alternates: { canonical: 'https://www.tikkitx.com/terms' },
  openGraph: {
    title: 'Terms & Conditions — Tikkit X',
    description: 'The terms and conditions governing your use of the Tikkit X event management platform.',
    url: 'https://www.tikkitx.com/terms',
    images: [{ url: '/og-image.jpg', width: 1200, height: 630, alt: 'Tikkit X Terms & Conditions' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Terms & Conditions — Tikkit X',
    description: 'The terms and conditions governing your use of the Tikkit X event management platform.',
    images: ['/og-image.jpg'],
  },
}

export default function TermsPage() {
  return (
    <div style={{ background: '#080A10', minHeight: '100vh', color: '#E8EAF0' }}>
      {/* Nav */}
      <nav style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', maxWidth: 1100, margin: '0 auto' }}>
        <Link href="/" style={{ textDecoration: 'none' }}>
          <TikkitXLogo size="sm" />
        </Link>
        <Link href="/privacy" style={{ fontSize: 13, color: '#7A8494', textDecoration: 'none' }}>
          Privacy Policy →
        </Link>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: 760, margin: '0 auto', padding: '60px 24px 100px' }}>
        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 12, fontWeight: 600, letterSpacing: '0.1em', color: '#00C2FF', textTransform: 'uppercase', marginBottom: 12 }}>Legal</p>
          <h1 style={{ fontSize: 40, fontWeight: 800, color: '#fff', letterSpacing: '-0.03em', lineHeight: 1.1, marginBottom: 16 }}>Terms &amp; Conditions</h1>
          <p style={{ fontSize: 14, color: '#7A8494', lineHeight: 1.6 }}>
            Effective Date: 1 April 2026 &nbsp;|&nbsp; Last Updated: 1 April 2026
          </p>
          <div style={{ marginTop: 24, padding: '16px 20px', background: 'rgba(0,194,255,0.06)', border: '1px solid rgba(0,194,255,0.15)', borderRadius: 10, fontSize: 14, color: '#9AAAB8', lineHeight: 1.7 }}>
            These Terms and Conditions constitute a legally binding agreement between you and Two Bit Digital (SMC-PVT) LTD, trading as Tikkit X, governing your access to and use of the Tikkit X platform. By using the Platform, you agree to be bound by these Terms.
          </div>
        </div>

        {/* Sections */}
        <LegalSection number="1" title="Introduction and Acceptance">
          <p>These Terms and Conditions ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Two Bit Digital (SMC-PVT) LTD, trading as Tikkit X ("Tikkit X," "we," "us," or "our"), governing your access to and use of the Tikkit X platform, including our website at tikkitx.com, our mobile applications, and all related services (collectively, the "Platform").</p>
          <p>Two Bit Digital (SMC-PVT) LTD is a software development and automation studio registered in Pakistan, operating as the developer and operator of the Tikkit X Platform.</p>
          <p>By accessing or using the Platform, creating an account, purchasing a ticket, or registering for an event, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you must not access or use the Platform.</p>
        </LegalSection>

        <LegalSection number="2" title="Definitions">
          <p>Throughout these Terms, the following defined terms shall apply:</p>
          <ul>
            <li><strong>"Attendee"</strong> means any individual who registers for, purchases a ticket to, or attends an Event through the Platform.</li>
            <li><strong>"Event"</strong> means any live event, gathering, concert, workshop, conference, or similar experience listed on the Platform by an Organiser.</li>
            <li><strong>"Event Organiser" or "Organiser"</strong> means any individual or entity that creates, manages, and hosts Events using the Platform.</li>
            <li><strong>"Expression of Interest" or "EOI"</strong> means a registration mode in which an Attendee submits a request to attend an Event, subject to approval by the Organiser.</li>
            <li><strong>"Guest List"</strong> means the list of approved Attendees for an Event, managed and owned by the Organiser through the Platform.</li>
            <li><strong>"QR Code"</strong> means the cryptographically signed quick response code generated by the Platform for event entry verification.</li>
            <li><strong>"Ticket"</strong> means the digital right of entry to an Event, represented by a QR Code within the Platform.</li>
            <li><strong>"Vendor"</strong> means any service provider (photographer, DJ, caterer, AV supplier, security provider, or similar) that offers services through or in connection with the Platform.</li>
            <li><strong>"Tikkit X"</strong> refers to the broader Tikkit X ecosystem, including Tikkit X Artists, Tikkit X Vendors, and any related sub-brands or extensions of the Platform.</li>
          </ul>
        </LegalSection>

        <LegalSection number="3" title="Eligibility">
          <p>To use the Platform, you must:</p>
          <ul>
            <li>Be at least 18 years of age, or the age of legal majority in your jurisdiction, whichever is higher.</li>
            <li>Have the legal capacity to enter into a binding agreement.</li>
            <li>Provide accurate and truthful registration information.</li>
            <li>Not have been previously suspended or removed from the Platform.</li>
          </ul>
          <p>If you are using the Platform on behalf of an organisation, you represent and warrant that you have authority to bind that organisation to these Terms.</p>
        </LegalSection>

        <LegalSection number="4" title="Account Registration and Security">
          <SubSection title="4.1 Account Creation">
            <p>To access certain features of the Platform, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete.</p>
          </SubSection>
          <SubSection title="4.2 Account Security">
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to:</p>
            <ul>
              <li>Maintain the security of your login credentials and not share them with any third party.</li>
              <li>Immediately notify Tikkit X at <a href="mailto:admin@tikkitx.com" style={{ color: '#00C2FF' }}>admin@tikkitx.com</a> of any unauthorised access to or use of your account.</li>
              <li>Accept responsibility for all activities conducted through your account, whether or not authorised by you.</li>
            </ul>
          </SubSection>
          <SubSection title="4.3 Identity Verification">
            <p>Tikkit X may require identity verification at registration or at any time during your use of the Platform. Verification may include email verification, identity document verification (such as CNIC, passport, or national ID), and payment method verification. Failure to complete verification may result in restricted access to the Platform or specific Events.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="5" title="Event Registration and Ticketing">
          <SubSection title="5.1 Registration Modes">
            <p>Events on the Platform may operate under one of three registration modes, as determined by the Organiser:</p>
            <ul>
              <li><strong>Invite-Only:</strong> Access is restricted to individuals specifically invited by the Organiser.</li>
              <li><strong>Open Registration:</strong> Any eligible user may register for the Event, subject to capacity.</li>
              <li><strong>Expression of Interest (EOI):</strong> Users submit an EOI and the Organiser approves or declines attendance at their sole discretion.</li>
            </ul>
            <p>The Organiser retains absolute discretion over attendee approval, Guest List management, and capacity limits. Tikkit X does not guarantee admission to any Event.</p>
          </SubSection>
          <SubSection title="5.2 QR Code Tickets">
            <p>Upon approval and completion of any required payment, Attendees will receive a cryptographically signed QR Code through the Platform. This QR Code constitutes your Ticket and is:</p>
            <ul>
              <li><strong>Non-transferable:</strong> Your QR Code is bound to your verified identity and cannot be transferred, sold, shared, or assigned to any other person.</li>
              <li><strong>Non-reproducible:</strong> Attempts to screenshot, duplicate, photograph, or otherwise reproduce QR Codes may render the Ticket invalid.</li>
              <li><strong>Revocable:</strong> The Organiser and Tikkit X reserve the right to revoke any QR Code at any time for breach of these Terms, suspected fraud, or at the Organiser's discretion.</li>
            </ul>
          </SubSection>
          <SubSection title="5.3 Prohibition on Resale and Scalping">
            <p>You expressly agree that you will not:</p>
            <ul>
              <li>Resell, offer to resell, or facilitate the resale of any Ticket at any price, whether above, at, or below face value.</li>
              <li>Use any automated software, bot, macro, or similar tool to purchase Tickets or circumvent any purchase limitations.</li>
              <li>Advertise or list Tickets for sale on any third-party platform, social media, or marketplace.</li>
            </ul>
            <p>Violation of this clause will result in immediate account suspension, cancellation of all associated Tickets without refund, and may result in a permanent ban from the Platform. Tikkit X reserves the right to pursue legal remedies for any losses arising from scalping activities.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="6" title="Payments and Fees">
          <SubSection title="6.1 Ticket Pricing">
            <p>Ticket prices are set by Event Organisers. Tikkit X may charge a service fee and/or payment processing fee in addition to the ticket price. All applicable fees will be clearly displayed before you complete your purchase.</p>
          </SubSection>
          <SubSection title="6.2 Payment Methods">
            <p>The Platform supports payment methods as available in your jurisdiction, which may include bank transfer (IBFT), mobile wallets (JazzCash, EasyPaisa), card payments, and other methods integrated through our payment processing partners. You agree to comply with the terms of your payment provider in addition to these Terms.</p>
          </SubSection>
          <SubSection title="6.3 Payment Verification">
            <p>Where payment is made via screenshot submission or manual transfer, Tikkit X and/or the Organiser will verify receipt before confirming your Ticket. Tikkit X is not responsible for delays or failures in payment verification caused by incomplete payment information, banking errors, or third-party payment provider issues.</p>
          </SubSection>
          <SubSection title="6.4 Refund Policy">
            <p>Refund policies are determined by individual Event Organisers and will be displayed on the Event listing. Unless otherwise stated by the Organiser:</p>
            <ul>
              <li>Tickets are generally non-refundable once confirmed.</li>
              <li>If an Event is cancelled by the Organiser, you are entitled to a full refund of the ticket price (excluding service fees) within 30 days of cancellation.</li>
              <li>If an Event is rescheduled, your Ticket will remain valid for the new date. If you cannot attend the rescheduled Event, you may request a refund from the Organiser, subject to their refund policy.</li>
              <li>Tikkit X service fees are non-refundable except where required by applicable law.</li>
            </ul>
          </SubSection>
        </LegalSection>

        <LegalSection number="7" title="Terms for Event Organisers">
          <SubSection title="7.1 Organiser Responsibilities">
            <p>If you use the Platform as an Event Organiser, you agree to:</p>
            <ul>
              <li>Provide accurate and complete Event information, including date, time, location, pricing, and any restrictions.</li>
              <li>Comply with all applicable laws, regulations, permits, and licensing requirements for your Event.</li>
              <li>Manage your Guest List in a fair and non-discriminatory manner, consistent with applicable law.</li>
              <li>Fulfil any commitments made to Attendees regarding the Event, including refund policies displayed on the Platform.</li>
              <li>Maintain adequate insurance and safety measures for your Event.</li>
              <li>Not use the Platform to host Events that are unlawful, harmful, fraudulent, or that violate any third party's rights.</li>
            </ul>
          </SubSection>
          <SubSection title="7.2 Guest List Ownership">
            <p>Organisers own the Guest List data for their Events and may manage approvals, rejections, and communications with Attendees through the Platform. Tikkit X processes Guest List data on behalf of the Organiser and will not share Guest List data with third parties except as required to provide the Platform's services or as required by law.</p>
          </SubSection>
          <SubSection title="7.3 Organiser Fees and Payouts">
            <p>Tikkit X will remit ticket sale proceeds to Organisers in accordance with the payout schedule and terms agreed at the time of Event creation, less any applicable Tikkit X service fees. Tikkit X reserves the right to withhold payouts in cases of suspected fraud, chargebacks, or breach of these Terms, pending investigation.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="8" title="Terms for Vendors (Tikkit X Vendors)">
          <p>If you register as a Vendor on the Platform:</p>
          <ul>
            <li>You represent that you are a legitimate business or sole trader with the necessary qualifications, licences, and insurance to provide the services you offer.</li>
            <li>You agree to provide accurate information about your services, pricing, availability, and portfolio.</li>
            <li>You acknowledge that Tikkit X may display verified performance metrics, including event history, rebook rates, and Organiser reviews, on your public profile.</li>
            <li>You agree that any bookings made through the Platform are subject to a marketplace service fee, the rate of which will be disclosed to you prior to accepting any booking.</li>
            <li>You are solely responsible for the quality and delivery of your services. Tikkit X acts as a marketplace facilitator and is not a party to any contract between you and an Organiser.</li>
          </ul>
        </LegalSection>

        <LegalSection number="9" title="Prohibited Conduct">
          <p>You agree not to:</p>
          <ul>
            <li>Use the Platform for any unlawful purpose or in violation of any applicable local, national, or international law.</li>
            <li>Provide false, misleading, or inaccurate information at any time, including during registration, identity verification, or Event creation.</li>
            <li>Attempt to gain unauthorised access to any part of the Platform, other users' accounts, or any systems or networks connected to the Platform.</li>
            <li>Interfere with or disrupt the integrity or performance of the Platform, including through the use of viruses, bots, scrapers, or denial-of-service attacks.</li>
            <li>Engage in ticket scalping, resale, or any form of unauthorised ticket distribution.</li>
            <li>Harass, abuse, threaten, or discriminate against any other user of the Platform.</li>
            <li>Circumvent, disable, or otherwise interfere with any security-related features of the Platform, including QR Code verification mechanisms.</li>
            <li>Use the Platform to collect personal data of other users without their explicit consent.</li>
            <li>Impersonate any person or entity, or falsely state or misrepresent your affiliation with any person or entity.</li>
          </ul>
        </LegalSection>

        <LegalSection number="10" title="Intellectual Property">
          <SubSection title="10.1 Tikkit X's Intellectual Property">
            <p>The Platform, including its design, code, algorithms, cryptographic verification systems, branding, logos, trademarks (including "Tikkit X," "Tikkit X," "Tikkit X Artists," "Tikkit X Vendors," and "Pulse"), and all content created by Tikkit X, are the exclusive intellectual property of Two Bit Digital (SMC-PVT) LTD. You are granted a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform for its intended purposes, subject to these Terms.</p>
          </SubSection>
          <SubSection title="10.2 User Content">
            <p>You retain ownership of content you upload to the Platform (such as Event descriptions, images, and profile information). By uploading content, you grant Tikkit X a worldwide, non-exclusive, royalty-free licence to use, display, reproduce, and distribute such content solely for the purpose of operating and promoting the Platform. You represent that you have all necessary rights to grant this licence.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="11" title="Limitation of Liability">
          <SubSection title="11.1 Platform Role">
            <p>Tikkit X operates as a technology platform connecting Event Organisers, Attendees, and Vendors. Tikkit X is not the organiser, host, or producer of any Event listed on the Platform. Tikkit X does not guarantee the quality, safety, legality, or suitability of any Event, Organiser, or Vendor.</p>
          </SubSection>
          <SubSection title="11.2 Disclaimer of Warranties">
            <p>The Platform is provided on an "as is" and "as available" basis, without warranties of any kind, whether express, implied, or statutory. Tikkit X does not warrant that the Platform will be uninterrupted, error-free, secure, or free of viruses or other harmful components.</p>
          </SubSection>
          <SubSection title="11.3 Limitation">
            <p>To the maximum extent permitted by applicable law, Tikkit X's total aggregate liability to you for all claims arising out of or relating to these Terms or the Platform shall not exceed the greater of: (a) the total fees paid by you to Tikkit X in the twelve (12) months immediately preceding the event giving rise to the claim; or (b) PKR 10,000 (or the equivalent in your local currency).</p>
          </SubSection>
          <SubSection title="11.4 Exclusion of Consequential Damages">
            <p>In no event shall Tikkit X be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, goodwill, or business opportunities, arising out of or in connection with your use of or inability to use the Platform, regardless of the theory of liability.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="12" title="Indemnification">
          <p>You agree to indemnify, defend, and hold harmless Tikkit X, Two Bit Digital (SMC-PVT) LTD, and their officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising out of or relating to:</p>
          <ul>
            <li>Your use of or access to the Platform.</li>
            <li>Your violation of these Terms.</li>
            <li>Your violation of any applicable law or regulation.</li>
            <li>Your violation of any third party's rights, including intellectual property rights.</li>
            <li>Any Event you organise, attend, or provide services for through the Platform.</li>
          </ul>
        </LegalSection>

        <LegalSection number="13" title="Termination">
          <p>Tikkit X may suspend or terminate your account and access to the Platform at any time, with or without cause, and with or without notice, including but not limited to cases where:</p>
          <ul>
            <li>You breach any provision of these Terms.</li>
            <li>Your identity verification fails or is found to be fraudulent.</li>
            <li>You engage in ticket scalping or other prohibited conduct.</li>
            <li>Tikkit X is required to do so by law or regulatory authority.</li>
          </ul>
          <p>You may terminate your account at any time by contacting <a href="mailto:admin@tikkitx.com" style={{ color: '#00C2FF' }}>admin@tikkitx.com</a>. Termination does not relieve you of any obligations incurred prior to termination, including any outstanding payment obligations.</p>
        </LegalSection>

        <LegalSection number="14" title="Dispute Resolution">
          <SubSection title="14.1 Between Users">
            <p>Disputes between Attendees and Organisers, or between Organisers and Vendors, are primarily the responsibility of the parties involved. Tikkit X may, at its sole discretion, facilitate communication or mediation between parties but is under no obligation to resolve disputes.</p>
          </SubSection>
          <SubSection title="14.2 Between You and Tikkit X">
            <p>Any dispute arising out of or relating to these Terms or the Platform shall first be attempted to be resolved through good faith negotiation. If the dispute cannot be resolved within thirty (30) days, it shall be submitted to binding arbitration under the Arbitration Act, 1940 of Pakistan, with the seat of arbitration in Karachi, Pakistan. The language of arbitration shall be English.</p>
          </SubSection>
        </LegalSection>

        <LegalSection number="15" title="Governing Law">
          <p>These Terms shall be governed by and construed in accordance with the laws of the Islamic Republic of Pakistan, without regard to its conflict of law principles. For users accessing the Platform from outside Pakistan, you agree to comply with all local laws that apply to your use of the Platform.</p>
        </LegalSection>

        <LegalSection number="16" title="Data Protection">
          <p>Your use of the Platform is subject to our <Link href="/privacy" style={{ color: '#00C2FF' }}>Privacy Policy</Link>, which is incorporated into these Terms by reference. By using the Platform, you consent to the collection, use, and processing of your personal data as described in the Privacy Policy.</p>
          <p>Tikkit X processes personal data in accordance with the Prevention of Electronic Crimes Act, 2016 (PECA) and applicable data protection standards. Where we offer services to users in the United Kingdom or European Economic Area, we additionally comply with the UK GDPR and EU GDPR as applicable.</p>
        </LegalSection>

        <LegalSection number="17" title="Modifications to Terms">
          <p>Tikkit X reserves the right to modify these Terms at any time. Material changes will be communicated to you via email or through a notice on the Platform at least fourteen (14) days before the changes take effect. Your continued use of the Platform after the effective date of any modification constitutes your acceptance of the modified Terms. If you do not agree to the modified Terms, you must discontinue use of the Platform.</p>
        </LegalSection>

        <LegalSection number="18" title="General Provisions">
          <ul>
            <li><strong>Severability:</strong> If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</li>
            <li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and Tikkit X regarding the Platform and supersede all prior agreements and understandings.</li>
            <li><strong>Waiver:</strong> The failure of Tikkit X to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</li>
            <li><strong>Assignment:</strong> You may not assign or transfer your rights or obligations under these Terms without Tikkit X's prior written consent. Tikkit X may assign its rights and obligations without restriction.</li>
            <li><strong>Force Majeure:</strong> Tikkit X shall not be liable for any delay or failure in performance resulting from causes beyond its reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, pandemics, government action, internet or telecommunications failures, or power outages.</li>
            <li><strong>Notices:</strong> All notices to Tikkit X should be sent to <a href="mailto:admin@tikkitx.com" style={{ color: '#00C2FF' }}>admin@tikkitx.com</a>. Notices to you will be sent to the email address associated with your account.</li>
          </ul>
        </LegalSection>

        <LegalSection number="19" title="Contact Information">
          <p>If you have any questions about these Terms, please contact us:</p>
          <div style={{ margin: '14px 0', padding: '14px 18px', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 8, fontSize: 14, color: '#9AAAB8', lineHeight: 1.8 }}>
            <strong style={{ color: '#C8D0DC', display: 'block' }}>Two Bit Digital (SMC-PVT) LTD, trading as Tikkit X</strong>
            Email: <a href="mailto:admin@tikkitx.com" style={{ color: '#00C2FF' }}>admin@tikkitx.com</a><br />
            Website: <a href="https://tikkitx.com" style={{ color: '#00C2FF' }}>https://tikkitx.com</a>
          </div>
        </LegalSection>
      </main>

      <style>{`
        main p { font-size: 15px; line-height: 1.75; color: #9AAAB8; margin-bottom: 14px; }
        main ul { padding-left: 20px; margin-bottom: 14px; }
        main ul li { font-size: 15px; line-height: 1.75; color: #9AAAB8; margin-bottom: 8px; }
        main strong { color: #C8D0DC; font-weight: 600; }
      `}</style>
      <SiteFooter />
    </div>
  )
}

function LegalSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 48, paddingBottom: 48, borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 20 }}>
        <span style={{ fontSize: 12, fontWeight: 700, color: '#00C2FF', opacity: 0.6, minWidth: 24 }}>{number}.</span>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: '#E8EAF0', letterSpacing: '-0.02em' }}>{title}</h2>
      </div>
      <div style={{ paddingLeft: 36 }}>{children}</div>
    </section>
  )
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <h3 style={{ fontSize: 14, fontWeight: 600, color: '#C8D0DC', marginBottom: 10 }}>{title}</h3>
      {children}
    </div>
  )
}
