-- Venues & Experiences Phase 1
-- Venue entity, programmes, programme instances, resources (slot booking), unified bookings

-- Venue categories
CREATE TYPE venue_category AS ENUM (
  'studio', 'court', 'hall', 'rooftop', 'garden', 'restaurant',
  'cafe', 'coworking', 'gym', 'pool', 'theatre', 'gallery', 'other'
);

-- Core venue entity
CREATE TABLE venues (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name          text NOT NULL,
  slug          text UNIQUE NOT NULL,
  city          text NOT NULL,
  address       text,
  lat           numeric(9,6),
  lng           numeric(9,6),
  categories    venue_category[] NOT NULL DEFAULT '{}',
  description   text,
  photos        text[] NOT NULL DEFAULT '{}',
  instagram     text,
  website       text,
  phone         text,
  capacity      integer,
  verified      boolean NOT NULL DEFAULT false,
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX venues_slug_idx  ON venues(slug);
CREATE INDEX venues_owner_idx ON venues(owner_id);
CREATE INDEX venues_city_idx  ON venues(city);

ALTER TABLE venues ENABLE ROW LEVEL SECURITY;

-- Public can read active/verified venues
CREATE POLICY venues_public_read ON venues
  FOR SELECT USING (active = true);

-- Owner can do everything
CREATE POLICY venues_owner_all ON venues
  USING (owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

-- Programmes (recurring experiences — weekly yoga, monthly comedy night, etc.)
CREATE TABLE programmes (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id              uuid NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  title                 text NOT NULL,
  description           text,
  category              text NOT NULL DEFAULT 'experience',
  rrule                 text,                   -- RFC 5545 RRULE string (e.g. FREQ=WEEKLY;BYDAY=SA)
  start_time            time NOT NULL,          -- wall-clock start (e.g. 18:30)
  duration_mins         integer NOT NULL DEFAULT 60,
  capacity              integer NOT NULL DEFAULT 20,
  price                 numeric(12,2) NOT NULL DEFAULT 0,
  currency              text NOT NULL DEFAULT 'PKR',
  cover_image           text,
  tags                  text[] NOT NULL DEFAULT '{}',
  spot_booking_enabled  boolean NOT NULL DEFAULT false,
  active                boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX programmes_venue_idx ON programmes(venue_id);

ALTER TABLE programmes ENABLE ROW LEVEL SECURITY;

CREATE POLICY programmes_public_read ON programmes
  FOR SELECT USING (active = true);

CREATE POLICY programmes_owner_all ON programmes
  USING (venue_id IN (SELECT id FROM venues WHERE owner_id = auth.uid()))
  WITH CHECK (venue_id IN (SELECT id FROM venues WHERE owner_id = auth.uid()));

-- Programme instances (materialised occurrences, generated by Edge Function cron daily, 60-day window)
CREATE TYPE programme_instance_status AS ENUM ('scheduled', 'live', 'cancelled', 'completed');

CREATE TABLE programme_instances (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  programme_id   uuid NOT NULL REFERENCES programmes(id) ON DELETE CASCADE,
  date           date NOT NULL,
  status         programme_instance_status NOT NULL DEFAULT 'scheduled',
  tickets_sold   integer NOT NULL DEFAULT 0,
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE(programme_id, date)
);

CREATE INDEX programme_instances_programme_idx ON programme_instances(programme_id);
CREATE INDEX programme_instances_date_idx      ON programme_instances(date);

ALTER TABLE programme_instances ENABLE ROW LEVEL SECURITY;

CREATE POLICY programme_instances_public_read ON programme_instances
  FOR SELECT USING (status IN ('scheduled', 'live'));

CREATE POLICY programme_instances_owner_all ON programme_instances
  USING (programme_id IN (
    SELECT p.id FROM programmes p
    JOIN venues v ON v.id = p.venue_id
    WHERE v.owner_id = auth.uid()
  ))
  WITH CHECK (programme_id IN (
    SELECT p.id FROM programmes p
    JOIN venues v ON v.id = p.venue_id
    WHERE v.owner_id = auth.uid()
  ));

-- Resources (bookable physical spaces — courts, studios, recording booths)
CREATE TYPE resource_duration_unit AS ENUM ('30', '60', '90', '120');

CREATE TABLE resources (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id            uuid NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  name                text NOT NULL,
  description         text,
  resource_type       text NOT NULL DEFAULT 'space',  -- court, studio, table, booth, etc.
  duration_unit_mins  integer NOT NULL DEFAULT 60,
  price_per_slot      numeric(12,2) NOT NULL DEFAULT 0,
  currency            text NOT NULL DEFAULT 'PKR',
  buffer_mins         integer NOT NULL DEFAULT 0,
  max_advance_days    integer NOT NULL DEFAULT 30,
  min_notice_hours    integer NOT NULL DEFAULT 2,
  open_time           time NOT NULL DEFAULT '08:00',
  close_time          time NOT NULL DEFAULT '22:00',
  active_days         integer[] NOT NULL DEFAULT '{1,2,3,4,5,6,7}',  -- 1=Mon, 7=Sun
  capacity            integer NOT NULL DEFAULT 1,
  photos              text[] NOT NULL DEFAULT '{}',
  active              boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX resources_venue_idx ON resources(venue_id);

ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY resources_public_read ON resources
  FOR SELECT USING (active = true);

CREATE POLICY resources_owner_all ON resources
  USING (venue_id IN (SELECT id FROM venues WHERE owner_id = auth.uid()))
  WITH CHECK (venue_id IN (SELECT id FROM venues WHERE owner_id = auth.uid()));

-- Slot bookings (on-demand, not pre-materialised)
CREATE TYPE slot_booking_status AS ENUM ('pending', 'confirmed', 'cancelled', 'completed', 'no_show');

CREATE TABLE slot_bookings (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id   uuid NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date          date NOT NULL,
  start_time    time NOT NULL,
  end_time      time NOT NULL,
  duration_mins integer NOT NULL,
  guest_count   integer NOT NULL DEFAULT 1,
  total_price   numeric(12,2) NOT NULL DEFAULT 0,
  currency      text NOT NULL DEFAULT 'PKR',
  status        slot_booking_status NOT NULL DEFAULT 'pending',
  notes         text,
  qr_token      text UNIQUE DEFAULT encode(gen_random_bytes(16), 'hex'),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX slot_bookings_resource_idx ON slot_bookings(resource_id, date);
CREATE INDEX slot_bookings_user_idx     ON slot_bookings(user_id);

ALTER TABLE slot_bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY slot_bookings_user_own ON slot_bookings
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY slot_bookings_user_insert ON slot_bookings
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY slot_bookings_user_cancel ON slot_bookings
  FOR UPDATE USING (user_id = auth.uid() AND status = 'pending');

CREATE POLICY slot_bookings_venue_owner ON slot_bookings
  FOR ALL USING (
    resource_id IN (
      SELECT r.id FROM resources r
      JOIN venues v ON v.id = r.venue_id
      WHERE v.owner_id = auth.uid()
    )
  );

NOTIFY pgrst, 'reload schema';
